kind: pipeline
type: docker
name: build
steps:
  - name: 依赖缓存
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: node_cache
        path: /cache

  - name: 编译文件
    image: node:14.15
    pull: if-not-exists # always never
    commands:
      - node -v
      - npm -v
      - npm install
      - npm run build

  # 更新缓存
  - name: 更新依赖缓存
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: node_cache
        path: /cache

  - name: 同步文件
    image: appleboy/drone-scp
    settings:
      host: 47.109.17.168
      username: root # 登录名
      password:
        from_secret: ssh_password # 登录密码
      port: 22
      command_timeout: 3m
      # 设置要将打包户的文件部署到的文件地址
      target: /home/test # 把项目拷贝到target目录
      overwrite: true
      source: dist/* # 打包后的那个目录
      rm: true

volumes:
  - name: node_cache
    host:
      path: /data/node
